### PR TITLE
appveyor deploy tags to github releases

### LINKED ISSUE #66: Appveyor Github Authentication token
@ecmnet In order for appveyor to upload to Github releases you have to generate a token on github and give it to appveyor. I don't have access to do this.

Instructions here "GitHub authentication token" - https://www.appveyor.com/docs/deployment/github

### PR DESCRIPTION
**Pull request by dagar**
- closes #66

### CODE REVIEW

**Comment by dagar** [comment]
We'll need to create a tag to see if the github token and configuration are correct.

**Comment by ecmnet** [comment]
Configuration seems to be correct. msi file is deployed.

**Comment by dagar** [comment]
Good. I don't have anything on my windows machine to test with, but it installs and runs.

**Comment by ecmnet** [comment]
Perfect. Thanks a lot for your contributions.

**Pull request merged**
