### PR TITLE
ant ivy for dependencies

### PR DESCRIPTION
**Pull request by dagar**
@ecmnet I've added ivy to the ant script to grab dependencies. We still need to go through and add entries in ivy.xml and then remove everything from lib/.

### CODE REVIEW

**Comment by dagar** [comment]
Still a few more dependencies to remove from the repo, and then need to do something with mavcomm and mavmq.
Can you review/test this?

**Comment by ecmnet** [comment]
@dagar mavmq removed as it is unused. mavcomm needs to be a submodule, I think

**Comment by dagar** [comment]
I can add it as a submodule, but how do you want to tie the builds together? A submodule will just be as if you clone mavcomm within the MAVGCL tree (wherever you want). 

That leaves 2 dependencies I haven't been able to pull into Ivy.

 - poly2tri-core-0.1.0.jar
  -  I could only find 0.1.1 and 0.1.2, and neither worked
 - jfxchartext-1.1.jar
  - I haven't been able to find this in a repo yet

**Comment by ecmnet** [comment]
jfxchartext-1.1.jar is zipped in https://bitbucket.org/emxsys/javafx-chart-extensions/downloads
poly2tri-core-0.1.0.jar not required anymore as I cleaned up (I removed some 3D experiments)

**Comment by dagar** [comment]
I still can't find jfxchartext in a repo anywhere, but it's only 60kb so I guess it's fine for now.

My knowledge of ant is pretty basic, but for mavcomm I think we just import it's build.xml in mavgcl. I'll do that in another PR. Please merge this pull request if it's working for you.

**Comment by ecmnet** [comment]
Currently the build crashes after launching on OSX. Investigating.

**Comment by ecmnet** [comment]
Thanks again. But still an issue. Some of the fxml files are not found.

**Comment by dagar** [comment]
hmm. I'll compare the original jars to what ivy grabbed.

**Comment by dagar** [comment]
Does this still fail for you? It's working for me on linux.

**Pull request closed without merging**
